### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by nic-oz** [sunuwars/DJES#20]
Good morning guys :sun_with_face: 
First impressions: 
- Easy to follow README.
Tip: Alternatively, postgres provides a command line you can use too, for steps 3-5, in case there is already a test user registered:
```
createdb toolshare -O sunuwars
```
(or –owner=sunuwars)

- Good file architecture and flow.
- Nice and simple concept to try out databases.

**Comment by thejoefriel** [comment]
Thanks very much! ❤️ 

The postgres tip is really useful! Going to update our readme with it so we don't forget. 

Thanks for the other nice words. It was definitely an interesting challenge this week!
